### ISSUE TITLE
unless / if in app/views/landing/index.html.erb

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#10]
You are checking the same thing twice in this file, and can replace the two with a single if logged_in? / else.

Also, you can do erb comments using `<%# blah %>` rather than code comments in erb tags.

**Comment by irisfaraway** [comment]
Fixed: https://github.com/irisfaraway/book-tracker/pull/15

**Comment by tomnatt** [comment]
:+1:
