### ISSUE TITLE
General code style

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#11]
It would be worth setting up rubocop in your editor with the rails plugins turned on and looking at the notifications - particularly in the controllers.

The one we use is here: https://github.bath.ac.uk/digital/coding-standards/blob/master/.rubocop.yml

**Comment by irisfaraway** [comment]
Set it up: https://github.com/irisfaraway/book-tracker/commit/88c699084071fba51139d59831252e03e8c85b6b Will tidy things up as I go.
