### ISSUE TITLE
app/views/books/new.html.erb template layout

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#12]
This template seems to have two distinct purposes - you might want to consider separating the google books returns and form filling functionality.

If you keep it together, you are using if / unless instead of an if / else. I would also recommend that you use `if blah.blank? && blah2.blank?` rather than the unless construction on line 11 as it seems to more logically reflect the intent of the template (it is functionally identical).

You should also sanitise the information provided by the books api before using it in your forms.

**Comment by irisfaraway** [comment]
Fixed: https://github.com/irisfaraway/book-tracker/pull/17

I sanitised and then unsanitised as it turns out Rails 3+ does this automatically.
