### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#22]
The tests do run - you need to use a postgres user with superuser powers. 

When running the tests, I get this result:
`18 tests, 15 assertions, 7 failures, 6 errors, 0 skips`

**Comment by irisfaraway** [comment]
The tests are no longer failing – but there are still some errors, which will hopefully be annihilated soon.

**Comment by tomnatt** [comment]
Some tips for the users test:
- use different users for different tests as you can't (and shouldn't try to) guarantee the order - as it stands, if the "destroy" test runs then a test which later updates the same user will fail
- the errors are reporting that the object calling `update` and `destroy` is `nil` [here](https://github.com/irisfaraway/book-tracker/blob/fix-tests/app/controllers/users_controller.rb#L50) and [here](https://github.com/irisfaraway/book-tracker/blob/fix-tests/app/controllers/users_controller.rb#L63) so you want to ask why that might be, and what might have changed to make that happen
- you should question the thinking behind [this line](https://github.com/irisfaraway/book-tracker/blob/fix-tests/app/controllers/users_controller.rb#L74)

**Comment by tomnatt** [comment]
Some tips for the books test:
- again, use different books for different tests
- the errors are reporting that the object calling `id` is `nil` [here](https://github.com/irisfaraway/book-tracker/blob/fix-tests/app/controllers/books_controller.rb#L81)
- is your test data valid and complete?

**Comment by tomnatt** [comment]
Also don't forget to fix the code layout in those test files!

**Comment by irisfaraway** [comment]
18 tests, 33 assertions, 0 failures, 0 errors, 0 skips 🎉
