### ISSUE TITLE
Date error on initial startup

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#5]
On initial startup I see: `undefined method 'start_date' for #<Book:0x007f80d4428108>`

Thrown by `app/views/books/_form.html.erb`

To reproduce:
- clean checkout w/ fresh postgres database
- run migrations
- start app
- Log in 
- Click "add book"

It seems your `create_books` migration creates a database field called `start` then you refer to `start_date` everywhere in the application. The same is true of `end` / `end_date`.

**Comment by irisfaraway** [comment]
This should be fixed now: https://github.com/irisfaraway/book-tracker/pull/13

**Comment by tomnatt** [comment]
Checked this and it's now working fine - thanks!
