### ISSUE TITLE
Unnecessary inclusion of ActiveModel::Validations

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#6]
Here:
https://github.com/irisfaraway/book-tracker/blob/master/app/models/book.rb#L2

You do not need this include as your book model is extending ActiveRecord::Base, which includes ActiveRecord::Validations which in turn includes ActiveModel::Validations.

**Comment by irisfaraway** [comment]
Fixed: https://github.com/irisfaraway/book-tracker/pull/14
