### ISSUE TITLE
Refactor to use scopes

### ISSUE THREAD

**Issue by tomnatt** [irisfaraway/book-tracker#8]
You have lots of raw sql in books_controller.rb which could be refactored to scopes in the model. This would make it much easier to test.

You should also consider refactoring the index to other methods or away into the model or a module to reduce the complexity of that method.

**Comment by irisfaraway** [comment]
I've split the book stats out into separate methods so the index is now less complex: https://github.com/irisfaraway/book-tracker/pull/16

Still need to do scopes though.

**Comment by irisfaraway** [comment]
Scopes scoped: https://github.com/irisfaraway/book-tracker/pull/19
